# site settings
title: Gold
subtitle: Blue
greetings: Gold Blue
email: dcfvg1992@naver.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: +82-(0)10-9747-7791

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/goldbluesupercar/
github_url:
gitlab_url:
youtube_url: https://www.youtube.com/channel/UC1zc1xfeJUTi6_eKH4SPNFg?view_as=subscriber
instagram_url: https://www.instagram.com/gold_blue_supercar/
linkedin_url:
pinterest_url:
slack_url:
blog_url: https://blog.naver.com/sgssaas
cafe_url: https://cafe.naver.com/goldbluesupercar

# build settings
markdown: kramdown

sass:
  style: compressed

theme: jekyll-theme-cayman
